FROM gcc:latest

RUN apt-get update && \
    apt-get install -y cmake build-essential libpq-dev libpqxx-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN mkdir build && cd build && \
    cmake .. && \
    make

CMD ["/app/build/server/kv_server"]